# tarot_card_dataclass.py
"""Card data class with class attributes, data attributes,
autogenerated methods and explicitly defined methods."""
from dataclasses import dataclass
from typing import ClassVar, List


@dataclass
class TarotCard:
    NAMES: ClassVar[List[str]] = ["Ace", "Two", "Three", "Four", "Five", "Six", "Seven", "Eight",
                                  "Nine", "Ten", "Page", "Knight", "Queen", "King"]
    SUITS: ClassVar[List[str]] = ["Cups", "Coins", "Swords", "Wands"]

    name: str
    suit: str

    """Define methods here:"""
